services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - "9000:9000"
    container_name: laravel-app
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - laravel
    expose:
      - "9000"

  db:
    image: postgres:17
    container_name: pgsql
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: horizon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel

  node:
    image: node:23
    container_name: laravel-node
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./Docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:

volumes:
  pgdata:
