services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - .:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - db
    networks:
      - laravel

  db:
    image: postgres:17
    container_name: pgsql
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: horizon_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel

  node:
    image: node:23
    container_name: laravel-node
    working_dir: /app
    volumes:
      - .:/app
    command: ["npm", "run", "dev"]
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:

volumes:
  pgdata:
